#!/usr/bin/env bash

set -uexo pipefail

ln -s /var/usrlocal /usr/local

dnf -y install cloud-init
ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants

dnf -y install firewalld
dnf -y install tmux
