#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install qemu-guest-agent

dnf -y install zram-generator-defaults

dnf -y install fail2ban

dnf -y install tmux vim tree
dnf -y install systemd-container # for machinectl

# For some reason nothing pulls network-online.target
# if this service isn't enabled...
# The service itself won't start due to an unmet condition
systemctl enable dnf5-makecache.timer

for m in /ctx/modules/*/ ; do
    env --chdir="$m" ./build
done
