name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    env:
      BUILD_REGISTRY: ghcr.io/${{ github.repository_owner }}
      BUILD_IMAGE: srv
      BUILD_BRANCH: 44
      BUILD_TAG: 44

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4

      - name: Pull
        id: pull
        run: |
          just pull

      - name: Build
        id: build
        run: just build

      - name: Rechunk
        id: rechunk
        run: |
          just rechunk

      - name: Login to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN_USER: ${{ github.actor }}
        run: |
          echo "${GITHUB_TOKEN}" | sudo podman login -u "${LOGIN_USER}" --password-stdin "ghcr.io"

      # TODO: remove me when we have a new podman in 26.04 runners
      # needed because old podman doesn't push layer annotations for
      # the rpm-ostree rechunker at all
      - name: Install Podman from Brew
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install podman

      - name: Push to GHCR
        id: push
        env:
          REGISTRY: ${{ env.BUILD_REGISTRY }}
          IMAGE: ${{ env.BUILD_IMAGE }}
          TAG: ${{ env.BUILD_TAG }}
          MAX_RETRIES: 3
        run: |
          set -x
          # HACK: push a second time so layer annotations are present
          # TODO: remove me when https://github.com/containers/podman/issues/27796 fixed
          for i in $(seq "${MAX_RETRIES}"); do
            sudo /home/linuxbrew/.linuxbrew/bin/podman push "$REGISTRY/$IMAGE:$TAG" && break || sleep $((5 * i));
          done

          for i in $(seq "${MAX_RETRIES}"); do
            sudo /home/linuxbrew/.linuxbrew/bin/podman push "$REGISTRY/$IMAGE:$TAG" && break || sleep $((5 * i));
          done
