name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      packages: write

    env:
      BUILD_REGISTRY: ghcr.io/${{ github.repository_owner }}
      BUILD_IMAGE: srv
      BUILD_BRANCH: 44
      BUILD_TAG: 44

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4

      - name: Pull
        id: pull
        run: |
          just pull

      - name: Build
        id: build
        run: just build

      - name: Login to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN_USER: ${{ github.actor }}
        run: |
          echo "${GITHUB_TOKEN}" | podman login -u "${LOGIN_USER}" --password-stdin "ghcr.io"
          echo "${GITHUB_TOKEN}" | docker login -u "${LOGIN_USER}" --password-stdin "ghcr.io" # for cosign

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.1

      - name: Push to GHCR
        id: push
        env:
          REGISTRY: ${{ env.BUILD_REGISTRY }}
          IMAGE: ${{ env.BUILD_IMAGE }}
          TAG: ${{ env.BUILD_TAG }}
          MAX_RETRIES: 3
        run: |
          set -x
          # HACK: push a second time so layer annotations are present
          # TODO: remove me when https://github.com/containers/podman/issues/27796 fixed
          for i in $(seq "${MAX_RETRIES}"); do
            podman push --digestfile=/tmp/digestfile "$REGISTRY/$IMAGE:$TAG" && break || sleep $((5 * i));
          done

          for i in $(seq "${MAX_RETRIES}"); do
            podman push --digestfile=/tmp/digestfile "$REGISTRY/$IMAGE:$TAG" && break || sleep $((5 * i));
          done

          echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"

      - name: Sign with cosign
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: just sign "${{ steps.push.outputs.digest }}"
